title: Prodotto
nav:
    - index.md
    - Mini-KVM:
        - minikvm/index.md
        - minikvm/whats-in-the-box.md
        - minikvm/features.md
        - ../app/basic.md
        - minikvm/how-to-connect.md
        - Come Funziona: /faq/usbkvm/kvm-over-usb/
        - Recensioni & Stampa: minikvm/reviews.md
        - minikvm/specifications.md
        - minikvm/usb-switch.md
        - minikvm/extension-pins.md
        - FAQ & Risoluzione Problemi: /faq/minikvm/op-minikvm/
        - Perché Openterface: /faq/usbkvm/openterface/
    - Accessori:
        - accessories/index.md
        - Cavo VGA a HDMI 1m: accessories/vga-to-hdmi-cable.md
        - Cavo Type-C a C Nylon 1.5m: accessories/nylong-c-to-c-150.md
        - Cavo Type-C a C Arancione 1.5m: accessories/type-c-to-c-cable-with-adapter.md
        - Cavo Type-C a A Nero 30cm: accessories/black-c-to-a-30.md
        - Cavo HDMI 30cm: accessories/hdmi-male-to-male-cable.md
        - Borsa Toolkit: accessories/openterface-toolkit-bag.md