flatten_single_child_sections: true
nav:
    - Casa: index.md
    - FAQ: faq
    - Prodotto: product
    - App: app
    - Casi d'Uso: use-cases.md
    - Recensioni: /product/minikvm/reviews/
    - Conformità: compliance.md
    - Negozio: https://shop.techxartisan.com
    - Discord: /discord
    - Blog: blog
    - Informazioni: about.md
